packages:
  - "**"

catalogs:
  default:
    "@itwin/imodel-browser-react": "^3.3.1"
    "@itwin/imodels-access-frontend": "^6.0.1"
    "@itwin/imodels-client-management": "^6.0.1"
    "@itwin/imodels-access-backend": "^6.0.1"
    "@itwin/presentation-components": "^5.12.9"
    "@microsoft/applicationinsights-web": "^3.3.10"
    "lz-string": "^1.5.0"
    "monaco-editor": "^0.53.0"
    "npm-run-all": "^4.1.5"
    "oidc-client-ts": "^3.3.0"

  itwinjs-core:
    "@itwin/appui-abstract": "^5.1.9"
    "@itwin/core-bentley": "^5.1.9"
    "@itwin/core-backend": "^5.1.9"
    "@itwin/core-common": "^5.1.9"
    "@itwin/core-frontend": "^5.1.9"
    "@itwin/core-geometry": "^5.1.9"
    "@itwin/core-i18n": "^5.1.9"
    "@itwin/core-markup": "^5.1.9"
    "@itwin/core-orbitgt": "^5.1.9"
    "@itwin/core-quantity": "^5.1.9"
    "@itwin/core-react": "^5.1.9"
    "@itwin/core-telemetry": "^5.1.9"
    "@itwin/ecschema-metadata": "^5.1.9"
    "@itwin/ecschema-rpcinterface-common": "^5.1.9"
    "@itwin/ecschema-rpcinterface-impl": "^5.1.9"
    "@itwin/express-server": "^5.1.9"
    "@itwin/presentation-backend": "^5.1.9"
    "@itwin/presentation-common": "^5.1.9"
    "@itwin/presentation-frontend": "^5.1.9"
    "@itwin/webgl-compatibility": "^5.1.9"

  appui:
    "@itwin/appui-react": "^5.15.1"
    "@itwin/core-react": "^5.15.1"
    "@itwin/components-react": "^5.15.1"
    "@itwin/imodel-components-react": "^5.15.1"

  itwinui:
    "@itwin/itwinui-icons-react": "^2.11.0"
    "@itwin/itwinui-illustrations-react": "^2.1.0"
    "@itwin/itwinui-layouts-css": "^0.4.0"
    "@itwin/itwinui-layouts-react": "^0.4.1"
    "@itwin/itwinui-react": "^3.19.4"

  react:
    "react": "^18.3.1"
    "react-dom": "^18.3.1"
    "react-error-boundary": "^6.0.0"
    "react-redux": "^7.2.9"
    "react-router": "^7.9.2"
    "redux": "^4.2.1"
    "@types/react": "^18.3.24"
    "@types/react-dom": "^18.3.7"
    "@types/react-redux": "^7.1.34"

  build-tools:
    "@itwin/eslint-plugin": "^5.2.1"
    "@types/node": "^22.18.6"
    "@types/path-browserify": "^1.0.3"
    "@vitejs/plugin-react": "^5.0.3"
    "cross-env": "^10.0.0"
    "cpx2": "^8.0.0"
    "dotenv": "^17.2.2"
    "eslint": "^9.36.0"
    "eslint-plugin-react": "^7.37.5"
    "npm-run-all": "^4.1.5"
    "sass": "^1.93.2"
    "tslib": "^2.8.1"
    "tsx": "^4.20.6"
    "typescript": "^5.9.2"
    "vite": "npm:rolldown-vite@latest"
    "vite-plugin-static-copy": "^3.1.2"
