packages:
  - '**'

catalogs:
  appui:
    '@itwin/appui-react': ^5.24.0
    '@itwin/components-react': ^5.24.0
    '@itwin/imodel-components-react': ^5.24.0
  build-tools:
    '@itwin/eslint-plugin': ^6.0.0
    '@types/node': ^25.1.0
    '@vitejs/plugin-react': ^5.1.2
    cpx2: ^8.0.0
    cross-env: ^10.1.0
    dotenv: ^17.2.3
    eslint: ^9.39.2
    eslint-plugin-react: ^7.37.5
    npm-run-all: ^4.1.5
    sass: ^1.97.3
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: 8.0.0-beta.11
    vite-plugin-static-copy: ^3.2.0
  default:
    '@itwin/imodels-access-backend': ^6.0.2
    '@itwin/imodels-access-frontend': ^6.0.2
    '@itwin/imodels-client-management': ^6.0.2
    '@itwin/presentation-components': ^5.12.17
    '@microsoft/applicationinsights-web': ^3.3.11
    lz-string: ^1.5.0
    monaco-editor: ^0.55.1
    npm-run-all: ^4.1.5
    oidc-client-ts: ^3.4.1
  itwinjs-core:
    '@itwin/appui-abstract': ^5.5.2
    '@itwin/core-backend': ^5.5.2
    '@itwin/core-bentley': ^5.5.2
    '@itwin/core-common': ^5.5.2
    '@itwin/core-frontend': ^5.5.2
    '@itwin/core-i18n': ^5.5.2
    '@itwin/core-quantity': ^5.5.2
    '@itwin/ecschema-metadata': ^5.5.2
    '@itwin/ecschema-rpcinterface-common': ^5.5.2
    '@itwin/ecschema-rpcinterface-impl': ^5.5.2
    '@itwin/express-server': ^5.5.2
    '@itwin/presentation-backend': ^5.5.2
    '@itwin/presentation-common': ^5.5.2
    '@itwin/presentation-frontend': ^5.5.2
  itwinui:
    '@itwin/itwinui-icons-react': ^2.11.0
    '@itwin/itwinui-illustrations-react': ^2.1.0
    '@itwin/itwinui-layouts-css': ^0.4.0
    '@itwin/itwinui-layouts-react': ^0.4.1
    '@itwin/itwinui-react': ^3.20.1
  react:
    '@types/react': ^18.3.27
    '@types/react-dom': ^18.3.7
    react: ^18.3.1
    react-dom: ^18.3.1
    react-error-boundary: ^6.1.0
    react-router: ^7.13.0
